import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Github, Linkedin } from "lucide-react";
import { FOUNDER_EXPERIENCE, PLATFORM_CONTRIBUTIONS, PROJECT_EVIDENCE } from "@/data/evidence-ledger";

export const metadata: Metadata = { title: "Tinotenda Brandon Duma — Founder of Radbit Studios", description: "Evidence-led profile of Tinotenda Brandon Duma: Zimbabwean full-stack product engineer, applied AI builder and founder of Radbit Studios.", alternates: { canonical: "/founders" }, openGraph: { title: "Tinotenda Brandon Duma — Founder of Radbit Studios", description: "Software implementation, product thinking and customer-facing delivery grounded in verifiable work.", type: "profile" } };

export default function FounderPage() { return <main>
  <header className="border-b border-border/60"><div className="container py-14 md:py-24"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Founder evidence record</p><div className="mt-6 grid gap-10 lg:grid-cols-[1.5fr_.6fr] lg:items-end"><div><h1 className="max-w-4xl font-headline text-5xl font-semibold tracking-tight md:text-6xl">Tinotenda Brandon Duma</h1><p className="mt-5 max-w-2xl text-xl leading-8 text-muted-foreground">Full-stack product engineer combining software implementation, product judgment and direct stakeholder delivery from Harare, Zimbabwe.</p></div><div className="border-l border-border pl-6"><p className="text-sm leading-6 text-muted-foreground">The operating principle is simple: understand the business problem, choose an appropriate architecture, build it, deploy it and remain accountable through launch and support.</p><div className="mt-5 flex gap-5"><a className="inline-flex items-center gap-2 text-sm hover:text-primary" href="https://github.com/TinzyWinzy" target="_blank" rel="noreferrer"><Github className="size-4" />GitHub</a><a className="inline-flex items-center gap-2 text-sm hover:text-primary" href="https://linkedin.com/in/tinotenda-duma-735a9797" target="_blank" rel="noreferrer"><Linkedin className="size-4" />LinkedIn</a></div></div></div></div></header>

  <section className="container grid gap-10 py-12 md:grid-cols-[.65fr_1.5fr] md:py-20"><div><p className="text-sm text-muted-foreground">Professional record</p><h2 className="mt-2 font-headline text-3xl font-semibold">Work that shaped the practice</h2></div><ol className="border-t border-border">{FOUNDER_EXPERIENCE.map(item => <li key={`${item.period}-${item.role}`} className="grid gap-3 border-b border-border py-6 sm:grid-cols-[7rem_1fr]"><span className="text-sm tabular-nums text-primary">{item.period}</span><div><h3 className="font-medium">{item.role}</h3><p className="mt-1 text-sm text-muted-foreground">{item.organisation}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{item.evidence}</p></div></li>)}</ol></section>

  <section className="border-y border-border/60 bg-muted/20"><div className="container py-12 md:py-20"><div className="max-w-3xl"><p className="text-sm text-muted-foreground">Evidence standard</p><h2 className="mt-2 font-headline text-3xl font-semibold">Proof states are part of the work.</h2><p className="mt-4 leading-7 text-muted-foreground">Radbit distinguishes what was built, demonstrated, deployed, validated, contributed to or independently researched. A prototype is not described as a production deployment. A security report is not described as accepted unless a third party confirms it.</p></div><div className="mt-9 flex flex-wrap gap-2">{["Built", "Demonstrated", "Deployed", "Validated", "Contributed", "Researched"].map(item => <span key={item} className="border border-border bg-background px-3 py-1.5 text-xs">{item}</span>)}</div></div></section>

  <section className="container py-12 md:py-20"><div className="mb-9"><p className="text-sm text-muted-foreground">Selected evidence</p><h2 className="mt-2 font-headline text-3xl font-semibold">Projects with inspectable artifacts</h2></div><div className="divide-y divide-border border-y border-border">{PROJECT_EVIDENCE.map((project, index) => <Link key={project.name} href={project.href} target={project.href.startsWith("http") ? "_blank" : undefined} rel={project.href.startsWith("http") ? "noreferrer" : undefined} className="group grid gap-3 py-6 md:grid-cols-[3rem_1fr_7rem_1.4fr_auto] md:items-center"><span className="text-xs text-muted-foreground">0{index + 1}</span><div><h3 className="font-headline text-lg font-semibold">{project.name}</h3><p className="text-xs text-muted-foreground">{project.sector}</p></div><span className="text-xs font-semibold uppercase tracking-wider text-primary">{project.state}</span><p className="text-sm leading-6 text-muted-foreground">{project.contribution}</p><ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link>)}</div></section>

  <section className="border-t border-border"><div className="container grid gap-9 py-12 md:grid-cols-[.7fr_1.5fr] md:py-16"><div><h2 className="font-headline text-2xl font-semibold">Platform delivery record</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">These are contribution records, not ownership claims or invented outcome metrics.</p></div><div className="divide-y divide-border border-y border-border">{PLATFORM_CONTRIBUTIONS.map(item => <div key={item.name} className="grid grid-cols-[1fr_7rem_7rem] gap-3 py-4 text-sm"><span className="font-medium">{item.name}</span><span className="text-muted-foreground">{item.platform}</span><span className="text-primary">{item.state}</span></div>)}</div></div></section>

  <section className="container py-14 md:py-20"><div className="max-w-3xl border-l-2 border-primary pl-7"><h2 className="font-headline text-3xl font-semibold">Bring the workflow, not a predetermined technology.</h2><p className="mt-4 text-muted-foreground">Radbit will help determine what should be built, what can be configured and what should remain manual.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 font-medium text-primary">Discuss a system <ArrowRight className="size-4" /></Link></div></section>
</main>; }
