/**
 * Registry for the Zimbabwe knowledge base.
 *
 * Keep this as plain ESM so scripts can inspect the source set without loading
 * the Next.js app, database, or embedding model.
 */
export const RAG_SOURCES = [
  {
    id: 'constitution-2023-excerpts',
    title: 'Constitution of Zimbabwe, consolidated to 2023',
    source: 'Constitution of Zimbabwe (2023)',
    category: 'constitution',
    locale: 'en',
    type: 'text',
    path: '../../database/constitution_excerpts.txt',
    canonicalPath: '../../Constitution Consolidated (2023).pdf',
    trust: 'primary',
    freshness: 'consolidated-2023',
    claimGuidance: 'Use for constitutional context. Quote section numbers only when present in the retrieved text.',
  },
  {
    id: 'nds2-key-sections',
    title: 'National Development Strategy 2, key sections',
    source: 'National Development Strategy 2 (2026-2030)',
    category: 'nds2',
    locale: 'en',
    type: 'text',
    path: '../../database/nds2_key_sections.txt',
    canonicalPath: '../../National Development Strategy 2 (NDS2) 2026-2030.pdf',
    trust: 'primary-policy',
    freshness: '2026-2030',
    claimGuidance: 'Use for policy direction and priorities. Treat targets as policy claims, not guaranteed outcomes.',
  },
  {
    id: 'nds2-sme',
    title: 'National Development Strategy 2, SME excerpts',
    source: 'National Development Strategy 2 (2026-2030)',
    category: 'nds2',
    locale: 'en',
    type: 'text',
    path: '../../database/nds2_sme.txt',
    canonicalPath: '../../National Development Strategy 2 (NDS2) 2026-2030.pdf',
    trust: 'primary-policy',
    freshness: '2026-2030',
    claimGuidance: 'Use for SME, enterprise development, and B2B strategy context.',
  },
  {
    id: 'zig-transactions-faq',
    title: 'ZiG Transactions FAQs',
    source: 'ZiG Transactions FAQs',
    category: 'zig_currency',
    locale: 'en',
    type: 'text',
    path: '../../database/ZiG Transactions FAQs__extract.txt',
    canonicalPath: '../../ZiG Transactions FAQs_.pdf',
    trust: 'official-guidance',
    freshness: '2024-transition-guidance',
    claimGuidance: 'Use for practical ZiG transition guidance. Mark exchange-rate or platform details as time-sensitive.',
  },
  {
    id: 'fiscal-device-gateway-api-v7-2',
    title: 'Fiscal Device Gateway API v7.2',
    source: 'Fiscal Device Gateway API v7.2',
    category: 'fiscal_device',
    locale: 'en',
    type: 'text',
    path: '../../database/Fiscal Device Gateway API v7.2 - clients_extract.txt',
    canonicalPath: '../../Fiscal Device Gateway API v7.2 - clients.pdf',
    trust: 'technical-specification',
    freshness: 'version-7.2',
    claimGuidance: 'Use for FDG integration behavior, endpoint names, and technical constraints.',
  },
  {
    id: 'licensed-agents-2026',
    title: 'Licensed agents for 2026',
    source: 'Licensed Agents 2026',
    category: 'licensed_agents',
    locale: 'en',
    type: 'text',
    path: '../../database/Lcensed agents for 2026__extract.txt',
    canonicalPath: '../../Lcensed agents for 2026_.pdf',
    trust: 'official-register',
    freshness: '2026',
    claimGuidance: 'Use as a dated register. Do not imply an agent remains licensed beyond the stated year.',
  },
  {
    id: 'health-sector-performance-q1-2025',
    title: '2025 Q1 abridged sector performance report',
    source: '2025 Q1 Sector Performance Report',
    category: 'sector_performance',
    locale: 'en',
    type: 'text',
    path: '../../database/2025-1st-Quarter-Abridged-Sector-Performance-Report-HMed_extract.txt',
    canonicalPath: '../../2025-1st-Quarter-Abridged-Sector-Performance-Report-HMed.pdf',
    trust: 'sector-report',
    freshness: '2025-Q1',
    claimGuidance: 'Use for dated sector evidence. Label figures by quarter and year.',
  },
  {
    id: 'zida-q1-2026-report',
    title: 'ZIDA quarterly report Q1 2026',
    source: 'ZIDA Quarterly Report Q1 2026',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_quarterly_report_q1_2026.txt',
    canonicalPath: '../../ZIDA QUARTERLY REPORT Q1 2026.pdf',
    trust: 'official-report',
    freshness: '2026-Q1',
    claimGuidance: 'Use for investment activity and dated figures. Always preserve the Q1 2026 time window.',
  },
  {
    id: 'zida-q1-2026-summary',
    title: 'ZIDA quarterly report Q1 2026 summary',
    source: 'ZIDA Q1 2026 Report Summary',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_q1_2026_report_summary.txt',
    trust: 'derived-summary',
    freshness: '2026-Q1',
    claimGuidance: 'Use as orientation only. Prefer the full ZIDA Q1 2026 report for exact figures.',
  },
  {
    id: 'zimra-tenders-public-notices-2026',
    title: 'ZIMRA tenders and public notices 2026',
    source: 'ZIMRA Tenders & Public Notices',
    category: 'zimra_tenders',
    locale: 'en',
    type: 'text',
    path: '../../database/zimra_tenders_public_notices_2026.txt',
    trust: 'public-notices',
    freshness: '2026',
    claimGuidance: 'Use for opportunity discovery and dated notices. Verify closing dates before advising clients.',
  },
  {
    id: 'zida-invest',
    title: 'ZIDA investment overview',
    source: 'ZIDA Invest Hub',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_invest.txt',
    trust: 'official-web-extract',
    freshness: 'scraped-2026-07-04',
    claimGuidance: 'Use for broad investor guidance. Verify live web pages for current fees or process changes.',
  },
  {
    id: 'zida-doing-business',
    title: 'ZIDA doing business in Zimbabwe',
    source: 'ZIDA Doing Business in Zimbabwe',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_doing_business.txt',
    trust: 'official-web-extract',
    freshness: 'scraped-2026-07-04',
    claimGuidance: 'Use for investor process framing. Treat procedural details as current only as of scrape date.',
  },
  {
    id: 'zida-agriculture',
    title: 'ZIDA agriculture sector',
    source: 'ZIDA Agriculture Sector',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_agriculture.txt',
    trust: 'official-web-extract',
    freshness: 'scraped-2026-07-04',
    claimGuidance: 'Use for agriculture opportunity framing.',
  },
  {
    id: 'zida-energy',
    title: 'ZIDA energy sector',
    source: 'ZIDA Energy Sector',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_energy.txt',
    trust: 'official-web-extract',
    freshness: 'scraped-2026-07-04',
    claimGuidance: 'Use for energy opportunity framing.',
  },
  {
    id: 'zida-mining',
    title: 'ZIDA mining sector',
    source: 'ZIDA Mining Sector',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_mining.txt',
    trust: 'official-web-extract',
    freshness: 'scraped-2026-07-04',
    claimGuidance: 'Use for mining opportunity framing.',
  },
  {
    id: 'zida-tourism',
    title: 'ZIDA tourism sector',
    source: 'ZIDA Tourism Sector',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_tourism.txt',
    trust: 'official-web-extract',
    freshness: 'scraped-2026-07-04',
    claimGuidance: 'Use for tourism opportunity framing.',
  },
  {
    id: 'zida-grow',
    title: 'ZIDA grow overview',
    source: 'ZIDA Grow',
    category: 'zida_investment',
    locale: 'en',
    type: 'text',
    path: '../../database/zida_grow.txt',
    trust: 'official-web-extract',
    freshness: 'scraped-2026-07-04',
    claimGuidance: 'Use for general expansion and growth messaging.',
  },
  {
    id: 'tourism-destination-zimbabwe-2018',
    title: 'Tourism Destination of Zimbabwe',
    source: 'Tourism Destination of Zimbabwe',
    category: 'tourism',
    locale: 'en',
    type: 'pdf',
    path: '../../TDoZ_2018_web-Copy.compressed1.pdf',
    trust: 'tourism-reference',
    freshness: '2018',
    enabled: false,
    claimGuidance: 'Disabled until the PDF extraction is validated; the current text extract is empty.',
  },
  {
    id: 'quality-policy',
    title: 'Quality Policy',
    source: 'Quality Policy',
    category: 'quality_policy',
    locale: 'en',
    type: 'pdf',
    path: '../../Quality Policy.pdf',
    trust: 'internal-policy',
    freshness: 'unknown',
    enabled: false,
    claimGuidance: 'Disabled until ownership, date, and relevance are confirmed.',
  },
  {
    id: 'nds2-trade-tourism-opportunities',
    title: 'NDS2 trade and tourism opportunities',
    source: 'National Development Strategy 2 (2026-2030)',
    category: 'nds2',
    locale: 'en',
    type: 'text',
    path: '../../database/nds2_toc.txt',
    trust: 'primary-policy',
    freshness: '2026-2030',
    claimGuidance: 'Use for trade and tourism opportunity lists from NDS2. Covers leather, processed foods, horticulture, textiles, tourism sites.',
  },
];
