import type { TenderSourceConfig } from './types';

export const TENDER_SOURCES: TenderSourceConfig[] = [
  // ── HTML Table scrapers ────────────────────────────────────────────
  {
    name: 'TendersOnTime',
    displayName: 'TendersOnTime',
    baseUrl: 'https://www.tendersontime.com',
    url: 'https://www.tendersontime.com/advance-search/',
    strategy: 'html-table',
    organization: 'TendersOnTime',
    category: 'Tender Notice',
  },
  {
    name: 'TendersInfo',
    displayName: 'TendersInfo',
    baseUrl: 'https://www.tendersinfo.com',
    url: 'https://www.tendersinfo.com/global-zimbabwe-tenders.php',
    strategy: 'html-table',
    organization: 'TendersInfo',
    category: 'Tender Notice',
  },
  {
    name: 'StanbicBank',
    displayName: 'Stanbic Bank',
    baseUrl: 'https://www.stanbicbank.co.zw',
    url: 'https://www.stanbicbank.co.zw/about-us/procurement',
    strategy: 'html-table',
    organization: 'Stanbic Bank Zimbabwe',
    sector: 'Financial Services',
    category: 'Banking Procurement',
  },
  {
    name: 'CBZ',
    displayName: 'CBZ Bank',
    baseUrl: 'https://www.cbz.co.zw',
    url: 'https://www.cbz.co.zw/tenders',
    strategy: 'html-table',
    organization: 'CBZ Bank',
    sector: 'Financial Services',
    category: 'Banking Procurement',
  },
  {
    name: 'Econet',
    displayName: 'Econet Wireless',
    baseUrl: 'https://www.econet.co.zw',
    url: 'https://www.econet.co.zw/procurement/',
    strategy: 'html-table',
    organization: 'Econet Wireless',
    sector: 'Telecommunications',
    category: 'Corporate Procurement',
  },
  {
    name: 'NetOne',
    displayName: 'NetOne',
    baseUrl: 'https://www.netone.co.zw',
    url: 'https://www.netone.co.zw/procurement',
    strategy: 'html-table',
    organization: 'NetOne',
    sector: 'Telecommunications',
    category: 'Corporate Procurement',
  },
  {
    name: 'TelOne',
    displayName: 'TelOne',
    baseUrl: 'https://www.telone.co.zw',
    url: 'https://www.telone.co.zw/procurement',
    strategy: 'html-table',
    organization: 'TelOne',
    sector: 'Telecommunications',
    category: 'Corporate Procurement',
  },
  {
    name: 'FBC',
    displayName: 'FBC Bank',
    baseUrl: 'https://www.fbc.co.zw',
    url: 'https://www.fbc.co.zw/tenders',
    strategy: 'html-table',
    organization: 'FBC Bank',
    sector: 'Financial Services',
    category: 'Banking Procurement',
  },
  {
    name: 'NMB',
    displayName: 'NMB Bank',
    baseUrl: 'https://www.nmbz.co.zw',
    url: 'https://www.nmbz.co.zw/about/procurement',
    strategy: 'html-table',
    organization: 'NMB Bank',
    sector: 'Financial Services',
    category: 'Banking Procurement',
  },
  {
    name: 'CABS',
    displayName: 'CABS',
    baseUrl: 'https://www.cabs.co.zw',
    url: 'https://www.cabs.co.zw/tenders',
    strategy: 'html-table',
    organization: 'CABS',
    sector: 'Financial Services',
    category: 'Banking Procurement',
  },
  {
    name: 'IDBZ',
    displayName: 'IDBZ',
    baseUrl: 'https://www.idbz.co.zw',
    url: 'https://www.idbz.co.zw/about-us/procurement',
    strategy: 'html-table',
    organization: 'IDBZ',
    sector: 'Financial Services',
    category: 'Procurement Notice',
  },
  {
    name: 'SAeTenders',
    displayName: 'South Africa eTenders',
    baseUrl: 'https://www.etenders.gov.za',
    url: 'https://www.etenders.gov.za',
    strategy: 'html-table',
    organization: 'South Africa eTenders',
    region: 'South Africa',
    category: 'Tender Notice',
    customParser: 'sa-etenders',
  },
  {
    name: 'AfDB',
    displayName: 'African Development Bank',
    baseUrl: 'https://www.afdb.org',
    url: 'https://www.afdb.org/en/projects-and-operations/tenders',
    strategy: 'html-table',
    organization: 'African Development Bank',
    region: 'Africa',
    category: 'International Development',
    requirements: ['AfDB vendor registration', 'International compliance'],
    customParser: 'afdb',
  },
  {
    name: 'OnlineTenders',
    displayName: 'OnlineTenders',
    baseUrl: 'https://www.onlinetenders.co.za',
    url: 'https://www.onlinetenders.co.za/tenders/zimbabwe',
    strategy: 'html-table',
    organization: 'OnlineTenders Zimbabwe',
    category: 'Tender Notice',
    customParser: 'online-tenders',
  },

  // ── HTML Links scrapers ────────────────────────────────────────────
  {
    name: 'USAID',
    displayName: 'USAID Zimbabwe',
    baseUrl: 'https://www.usaid.gov',
    url: 'https://www.usaid.gov/zimbabwe/work-with-us/partnership-opportunities',
    strategy: 'html-links',
    linkFilter: 'a[href*="tender"], a[href*="rfq"], a[href*="rfa"], a[href*="grant"], a[href*="opportunity"], a[href*="procurement"]',
    organization: 'USAID Zimbabwe',
    category: 'NGO / Development',
    requirements: ['USAID registration', 'DUNS number', 'SAM registration'],
  },
  {
    name: 'SADC',
    displayName: 'SADC',
    baseUrl: 'https://www.sadc.int',
    url: 'https://www.sadc.int/procurement-opportunities',
    strategy: 'html-links',
    linkFilter: 'a[href*="procurement"], a[href*="tender"], a[href*="bid"], a[href*="rfq"], a[href*="opportunity"]',
    organization: 'SADC',
    region: 'SADC',
    category: 'Tender Notice',
  },
  {
    name: 'PRAZ',
    displayName: 'PRAZ',
    baseUrl: 'https://www.praz.org.zw',
    url: 'https://www.praz.org.zw/tendering/',
    strategy: 'html-links',
    linkFilter: 'a[href*="tender"], a[href*="rfq"], a[href*="bid"], a[href*="procurement"], a[href*="notice"]',
    organization: 'PRAZ',
    category: 'Public Procurement',
  },
  {
    name: 'TenderLink',
    displayName: 'TenderLink Zimbabwe',
    baseUrl: 'https://tenderlink.co.zw',
    url: 'https://tenderlink.co.zw/',
    strategy: 'html-links',
    linkFilter: 'a[href*="tender"], a[href*="rfq"], a[href*="notice"], .post-title a, h2 a, h3 a, .entry-title a',
    organization: 'TenderLink Zimbabwe',
    category: 'Tender Notice',
  },
  {
    name: 'ETender',
    displayName: 'eTender Zimbabwe',
    baseUrl: 'https://etender.co.zw',
    url: 'https://etender.co.zw/',
    strategy: 'html-links',
    linkFilter: 'a[href*="listing"], a[href*="tender"], a[href*="opportunity"], .listing-title a, h2 a, h3 a',
    organization: 'eTender Zimbabwe',
    category: 'Tender Notice',
  },
  {
    name: 'TenderNoticeboard',
    displayName: 'Tender Noticeboard',
    baseUrl: 'https://tendernoticeboard.co.zw',
    url: 'https://tendernoticeboard.co.zw/',
    strategy: 'html-links',
    linkFilter: 'a[href*="tender"], a[href*="project"], a[href*="opportunity"], h2 a, h3 a, .card-title a, .post-title a',
    organization: 'Tender Noticeboard',
    category: 'Tender Notice',
  },
  {
    name: 'Classifieds',
    displayName: 'Classifieds Zimbabwe',
    baseUrl: 'https://www.classifieds.co.zw',
    url: 'https://www.classifieds.co.zw/',
    strategy: 'html-links',
    linkFilter: 'a[href*="tender"], a[href*="contract"], a[href*="procurement"], h2 a, h3 a, .card a, .listing a',
    organization: 'Classifieds Zimbabwe',
    category: 'Tender Notice',
  },
  {
    name: 'WorldBank',
    displayName: 'World Bank',
    baseUrl: 'https://www.worldbank.org',
    url: 'https://www.worldbank.org/en/projects/procurement',
    strategy: 'html-links',
    linkFilter: 'a[href*="procurement"], a[href*="tender"], a[href*="bid"], a[href*="rfq"]',
    organization: 'World Bank',
    category: 'International Development',
    requirements: ['World Bank vendor registration'],
    region: 'Global',
  },

  // ── HTML Divs scrapers ─────────────────────────────────────────────
  {
    name: 'GlobalTenders',
    displayName: 'GlobalTenders',
    baseUrl: 'https://www.globaltenders.com',
    url: 'https://www.globaltenders.com/zw/zimbabwe-vehicles-engines-tenders',
    strategy: 'html-divs',
    organization: 'GlobalTenders Zimbabwe',
    category: 'Tender Notice',
  },
  {
    name: 'BidDetail',
    displayName: 'BidDetail',
    baseUrl: 'https://www.biddetail.com',
    url: 'https://www.biddetail.com/zimbabwe-tenders',
    strategy: 'html-divs',
    organization: 'BidDetail Zimbabwe',
    category: 'Tender Notice',
    customParser: 'bid-detail',
  },
  {
    name: 'TenderInfoOrg',
    displayName: 'TenderInfo.Org',
    baseUrl: 'https://www.tenderinfo.org',
    url: 'https://www.tenderinfo.org/countries/zimbabwe',
    strategy: 'html-divs',
    organization: 'TenderInfo.Org',
    category: 'RFQ',
    customParser: 'tender-info-org',
  },
  {
    name: 'TendersZimbabwe',
    displayName: 'Tenders Zimbabwe',
    baseUrl: 'https://tenderszimbabwe.co.zw',
    url: 'https://tenderszimbabwe.co.zw/',
    strategy: 'html-divs',
    organization: 'Tenders Zimbabwe',
    category: 'Tender Notice',
    customParser: 'tenders-zimbabwe',
  },

  // ── Custom parsers ─────────────────────────────────────────────────
  {
    name: 'ZIMRA',
    displayName: 'ZIMRA',
    baseUrl: 'https://www.zimra.co.zw',
    url: 'https://www.zimra.co.zw/tenders',
    strategy: 'custom',
    organization: 'ZIMRA',
    category: 'Tender',
    customParser: 'zimra',
  },
  {
    name: 'UNDP',
    displayName: 'UNDP Zimbabwe',
    baseUrl: 'https://www.undp.org',
    url: 'https://www.undp.org/zimbabwe/procurement',
    strategy: 'custom',
    organization: 'UNDP Zimbabwe',
    category: 'UN Procurement',
    sector: 'Professional Services',
    requirements: ['UN Supplier registration required', 'Anti-fraud policy compliance'],
    customParser: 'undp',
  },
  {
    name: 'LiveTenders',
    displayName: 'proc.gov.zw',
    baseUrl: 'https://proc.gov.zw',
    url: 'https://proc.gov.zw/api/tenders',
    strategy: 'custom',
    organization: 'Government of Zimbabwe',
    category: 'Government Tender',
    customParser: 'live-tenders',
    timeout: 5000,
  },
];
