import { MetadataRoute } from "next";

const SITE_URL = (process.env.FRONTEND_URL || 'https://radbitstudios.co.zw').replace(/\/$/, '');

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        disallow: [
          '/api/',
          '/_next/',
          '/dashboard',
          '/settings',
          '/messages',
          '/notifications',
          '/news',
          '/export-assessment',
          '/budget-calculator',
          '/escrow',
          '/penalty-protection',
          '/zimra-fiscal-device-registration',
          '/compliant-receipts',
          '/tender-compliance-bridge',
          '/diaspora-matchmaking',
          '/features/praz-compliance',
          '/features/tax-copilot',
          '/resources/tools/fiscal-compliance',
          '/investor-portal',
          '/tax-copilot',
          '/vat-threshold-alerts',
          '/offline-mode',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/about',
          '/blog',
          '/consultancy',
          '/contact',
          '/diaspora',
          '/features/',
          '/services',
          '/work',
          '/pilot',
          '/events/',
          '/founders',
          '/intelligence',
          '/partners',
          '/pricing',
          '/privacy',
          '/resources',
          '/solutions',
          '/terms',
          '/threats',
          '/use-cases',
          '/guides/',
          '/sadc/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/about',
          '/blog',
          '/consultancy',
          '/contact',
          '/diaspora',
          '/features/',
          '/services',
          '/work',
          '/pilot',
          '/events/',
          '/founders',
          '/intelligence',
          '/partners',
          '/pricing',
          '/privacy',
          '/resources',
          '/solutions',
          '/terms',
          '/threats',
          '/use-cases',
          '/guides/',
          '/sadc/',
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
