version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      radix:
        patterns:
          - "@radix-ui/*"
      eslint:
        patterns:
          - "eslint*"
    ignore:
      - dependency-name: "next"
        versions: [">=15.0.0"]
