'use client';

import { useState, useContext } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, FileText, Download, DollarSign, CheckCircle2, AlertTriangle } from 'lucide-react';
import { AuthContext } from '@/contexts/auth-context';
import { useToast } from '@/hooks/use-toast';
import { checkAndDecrementUsage } from '@/services/usage-service';
import { UpgradeModal } from '@/components/upgrade-modal';
import type { UpgradeInfo } from '@/services/feature-gate';

export default function BidWriterPage() {
  const [tenderTitle, setTenderTitle] = useState('');
  const [tenderDescription, setTenderDescription] = useState('');
  const [organization, setOrganization] = useState('');
  const [closingDate, setClosingDate] = useState('');
  const [requirements, setRequirements] = useState('');
  const [businessName, setBusinessName] = useState('');
  const [businessDescription, setBusinessDescription] = useState('');
  const [currency, setCurrency] = useState<'USD' | 'ZiG' | 'ZAR'>('USD');
  const [loading, setLoading] = useState(false);
  const [proposal, setProposal] = useState<any>(null);
  const [upgradeInfo, setUpgradeInfo] = useState<UpgradeInfo | null>(null);
  const { user } = useContext(AuthContext);
  const { toast } = useToast();

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      toast({ title: 'Sign in required', description: 'Please sign in to use the Bid Writer.', variant: 'destructive' });
      return;
    }

    const access = await checkAndDecrementUsage(user.uid, 'tenderProposal');
    if (!access.success) {
      if (access.upgrade) {
        setUpgradeInfo(access.upgrade);
      } else {
        toast({ title: 'Usage limit reached', description: access.message, variant: 'destructive' });
      }
      return;
    }

    setLoading(true);
    try {
      const { generateTenderProposal } = await import('@/ai/flows/generate-tender-proposal');
      const result = await generateTenderProposal({
        tenderTitle,
        tenderDescription,
        organization,
        closingDate: closingDate || undefined,
        requirements: requirements.split('\n').filter(Boolean),
        businessName: businessName || undefined,
        businessDescription: businessDescription || undefined,
        currency,
      });
      setProposal(result);
    } catch (err: any) {
      toast({ title: 'Generation failed', description: err.message || 'Please try again.', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!proposal) return;
    const text = `BID PROPOSAL
============
Tender: ${tenderTitle}
Organization: ${organization}
Date: ${new Date().toLocaleDateString('en-ZW')}

EXECUTIVE SUMMARY
${proposal.executiveSummary}

TECHNICAL APPROACH
${proposal.technicalApproach}

TEAM QUALIFICATION
${proposal.teamQualification}

FINANCIAL PROPOSAL (${currency})
${proposal.financialProposal}

COMPLIANCE CHECKLIST
${proposal.complianceChecklist.map((c: string) => `  ✓ ${c}`).join('\n')}

RISK MITIGATION
${proposal.riskMitigation.map((r: string) => `  • ${r}`).join('\n')}

Generated by Radbit SME Hub Bid Writer`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `proposal-${tenderTitle.slice(0, 30).replace(/[^a-zA-Z0-9]/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight">AI Bid Writer</h1>
        <p className="text-muted-foreground">
          Generate a compliant, multi-currency proposal from any tender document.
        </p>
      </div>

      <div className="grid md:grid-cols-5 gap-8">
        <div className="md:col-span-2 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Tender Details</CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleGenerate} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="title">Tender Title *</Label>
                  <Input id="title" value={tenderTitle} onChange={e => setTenderTitle(e.target.value)} required placeholder="e.g. Supply of IT Equipment" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="org">Organization *</Label>
                  <Input id="org" value={organization} onChange={e => setOrganization(e.target.value)} required placeholder="e.g. Ministry of Health" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="desc">Tender Description</Label>
                  <Textarea id="desc" rows={3} value={tenderDescription} onChange={e => setTenderDescription(e.target.value)} placeholder="Paste the tender scope here..." />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-2">
                    <Label htmlFor="date">Closing Date</Label>
                    <Input id="date" type="date" value={closingDate} onChange={e => setClosingDate(e.target.value)} />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="currency">Currency</Label>
                    <select id="currency" value={currency} onChange={e => setCurrency(e.target.value as any)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">
                      <option value="USD">USD</option>
                      <option value="ZiG">ZiG</option>
                      <option value="ZAR">ZAR</option>
                    </select>
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="reqs">Requirements (one per line)</Label>
                  <Textarea id="reqs" rows={3} value={requirements} onChange={e => setRequirements(e.target.value)} placeholder="Valid tax clearance&#10;Business registration&#10;NRA compliance" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="biz">Your Business Name</Label>
                  <Input id="biz" value={businessName} onChange={e => setBusinessName(e.target.value)} placeholder="e.g. Mbare Tech Solutions" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="bizdesc">Business Profile</Label>
                  <Textarea id="bizdesc" rows={2} value={businessDescription} onChange={e => setBusinessDescription(e.target.value)} placeholder="Brief description of your business..." />
                </div>
                <Button type="submit" disabled={loading} className="w-full">
                  {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileText className="mr-2 h-4 w-4" />}
                  {loading ? 'Generating...' : 'Generate Proposal'}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>

        <div className="md:col-span-3 space-y-4">
          {!proposal ? (
            <Card>
              <CardContent className="py-16 text-center text-muted-foreground">
                <FileText className="h-12 w-12 mx-auto mb-4 opacity-30" />
                <p>Fill in the tender details and generate a proposal.</p>
                <p className="text-sm mt-2">Proposal includes executive summary, technical approach, financials, and compliance checklist.</p>
              </CardContent>
            </Card>
          ) : (
            <>
              <div className="flex justify-end">
                <Button variant="outline" onClick={handleDownload}>
                  <Download className="mr-2 h-4 w-4" /> Download Proposal
                </Button>
              </div>

              <Card>
                <CardHeader>
                  <CardTitle>Executive Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground leading-relaxed">{proposal.executiveSummary}</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Technical Approach</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground leading-relaxed whitespace-pre-line">{proposal.technicalApproach}</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Team Qualification</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground leading-relaxed whitespace-pre-line">{proposal.teamQualification}</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <DollarSign className="h-5 w-5 text-primary" />
                    Financial Proposal ({currency})
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground leading-relaxed whitespace-pre-line">{proposal.financialProposal}</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CheckCircle2 className="h-5 w-5 text-green-500" />
                    Compliance Checklist
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {proposal.complianceChecklist.map((item: string, i: number) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                        <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0 mt-0.5" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <AlertTriangle className="h-5 w-5 text-amber-500" />
                    Risk Mitigation
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {proposal.riskMitigation.map((item: string, i: number) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                        <AlertTriangle className="h-4 w-4 text-amber-500 shrink-0 mt-0.5" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </>
          )}
        </div>
      </div>

      <UpgradeModal
        open={!!upgradeInfo}
        onOpenChange={(o) => { if (!o) setUpgradeInfo(null); }}
        upgrade={upgradeInfo}
        onUpgrade={() => window.location.href = '/settings?tab=plan'}
      />
    </div>
  );
}
